import { z } from 'zod';

/**
 * Racing Domain: The "Last Piece" Scale
 * Governing the transition from Trend -> Physics (TORCS) -> Render (UE5)
 */

export const SimulationContractSchema = z.object({
  carId: z.string().describe("Target car ID for TORCS (e.g., 'cr-supercar')"),
  trackId: z.string().describe("Target track for simulation (e.g., 'monza', 'birmingham')"),
  weather: z.enum(['sunny', 'rainy', 'overcast', 'clear', 'light_rain', 'heavy_rain', 'fog']).default('sunny'),
  simulationType: z.enum(['speed_test', 'lap_time', 'collision_test', 'race', 'qualifying']).default('speed_test'),
  telemetryPoints: z.array(z.string()).optional().describe("Specific points to capture (RPM, Speed, etc.)"),
  gsiScore: z.number().min(0).max(1).optional().describe("Geometric Signal Integrity score from TriadGAT")
});

export const CinematicContractSchema = z.object({
  resolution: z.enum(['1080p', '4k', '8k']).default('1080p'),
  cameraModes: z.array(z.enum(['cinematic', 'onboard', 'drone', 'action', 'static', 'cockpit', 'chase', 'aerial', 'tv_broadcast', 'cinematic_orbit'])).min(1),
  footageLengthSeconds: z.number().min(5).max(300).default(15),
  lightingMood: z.string().default('natural')
});

export const JournalistContractSchema = z.object({
  headline: z.string().min(5).max(100),
  sentiment: z.number().min(-1).max(1), // -1 (negative) to 1 (positive)
  trendingSource: z.string().url().optional(),
  targetBot: z.string().default("@SARN_Bot"),
  sector: z.string().default("racing")
});

export const RacingDomainSchema = z.object({
  simulation: SimulationContractSchema,
  cinematic: CinematicContractSchema,
  journalism: JournalistContractSchema,
  
  // Advanced Pipeline Transitions
  compressionMetadata: z.object({
    source: z.string().describe("Source of compression (e.g. 'TriadGAT')"),
    latentVectorMean: z.number().optional(),
    graphNodesCount: z.number().optional(),
    compressionRatio: z.number().optional()
  }).optional(),
  
  visualReference: z.object({
    grokImagePrompt: z.string().describe("The prompt generated by Grok for the initial reference image"),
    referenceImageUrl: z.string().url().optional(),
    styleGuide: z.enum(['photorealistic', 'stylized_racing', 'cyberpunk_track']).default('photorealistic')
  }).optional(),
  
  stateTracking: z.object({
    nocoDbRecordId: z.string().optional(),
    workflowId: z.string().optional(),
    agentChain: z.array(z.string()).default(['TrendRadar', 'TriadGAT', 'Grok', 'TORCS', 'UE5'])
  }).optional(),

  enforcePhysicsGroundTruth: z.boolean().default(true)
});

export type RacingDomain = z.infer<typeof RacingDomainSchema>;
